# Codemagic workflow configuration for iOS release builds
workflows:
  ios_release:
    name: iOS Release (Xcode 16.2)
    environment:
      xcode: 16.2
      flutter: stable
      vars:
        BUNDLE_ID: com.example.sansebassms
      groups:
        - app_store_connect
    scripts:
      - name: Pre-build (deps, pods, firma, logging)
        script: |
          chmod +x ./pre-build.sh
          ./pre-build.sh
      - name: Build IPA (Release)
        script: |
          flutter build ipa --release --export-options-plist /Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - artifacts/*
      - codemagic_prebuild.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
