workflows:
  build-ios:
    name: Build iOS IPA
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    integrations:
      app_store_connect: CodemagicKey

    scripts:
      - name: Pre-cache and clean
        script: |
          flutter precache --ios
          flutter pub get
          flutter clean

      - name: Generate Flutter.podspec manually
        script: |
          mkdir -p ios/Flutter
          cat > ios/Flutter/Flutter.podspec <<EOF
          Pod::Spec.new do |s|
            s.name             = 'Flutter'
            s.version          = '1.0.0'
            s.summary          = 'Flutter framework'
            s.description      = <<-DESC
                                  Flutter iOS engine
                                 DESC
            s.homepage         = 'https://flutter.dev'
            s.license          = { :type => 'BSD' }
            s.author           = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
            s.source           = { :http => 'https://flutter.dev' }
            s.source_files     = '**/*'
            s.public_header_files = '**/*.h'
            s.module_map       = 'module.modulemap'
            s.platform         = :ios, '11.0'
          end
          EOF

      - name: Build IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
