workflows:
  ios-release:
    environment:
      groups:
        - app_store_connect
      xcode: latest
    scripts:
      - name: Generar GoogleService-Info.plist (seguro)
        script: |
          set -euo pipefail
          bash tool/prebuild_plist.sh

      - name: Instalar dependencias y CocoaPods
        script: |
          set -euo pipefail
          echo "== POD INSTALL ==" | tee -a build.log
          flutter pub get 2>&1 | tee -a build.log
          cd ios
          pod install --repo-update 2>&1 | tee -a ../build.log
          cd ..

      - name: Compilar IPA release
        script: |
          set -euo pipefail
          echo "== FLUTTER BUILD ==" | tee -a build.log
          flutter clean 2>&1 | tee -a build.log
          flutter pub get 2>&1 | tee -a build.log
          # Runner.xcworkspace is used automatically; Codemagic signs on export/publish
          flutter build ipa --release --no-codesign --build-number=${BUILD_NUMBER:-1} 2>&1 | tee -a build.log

      - name: Empaquetar logs
        script: |
          set -e
          zip -r build.log.zip build || true

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build.log
      - build.log.zip
      - prebuild_plist.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
