workflows:
  ios-build-and-publish:
    name: iOS Build and Publish to App Store
    max_build_duration: 45
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.sansebassms"
        APP_STORE_CONNECT_ISSUER_ID: "0bae98e1-a493-4ddc-ab5d-cdb87b225a1b"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "43Z3JZ75L6"
      groups:
        - app_store_credentials # contiene APP_STORE_CONNECT_PRIVATE_KEY en base64
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Precache and build Flutter iOS
        script: |
          flutter pub get
          flutter precache --ios
          flutter build ios --release --no-codesign

      - name: Copy Flutter.podspec if missing
        script: |
          PODSPEC_PATH="$FLUTTER_ROOT/bin/cache/artifacts/engine/ios/Flutter.podspec"
          if [ ! -f "$PODSPEC_PATH" ]; then
            echo "⚠️ Flutter.podspec no encontrado, copiando manualmente..."
            cp "$FLUTTER_ROOT/packages/flutter_tools/templates/cocoapods/Flutter.podspec" "$PODSPEC_PATH"
          fi

      - name: Run CocoaPods install
        script: |
          cd ios
          pod install

      - name: Decode private key from base64
        script: |
          echo $APP_STORE_CONNECT_PRIVATE_KEY | base64 --decode > /tmp/AuthKey.p8

      - name: Set up keychain and fetch provisioning
        script: |
          keychain initialize
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key /tmp/AuthKey.p8
          keychain add-certificates

      - name: Build IPA
        script: |
          xcode-project use-profiles
          xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner

      - name: Publish to App Store Connect
        script: |
          app-store-connect publish \
            --path build/ios/ipa/*.ipa \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key /tmp/AuthKey.p8

    artifacts:
      - build/ios/ipa/*.ipa
