workflows:
  build_app:
    name: Build Android and iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_STORE_ID: 6749592028
        BUNDLE_ID: com.example.sansebassms # <-- usa el tuyo real
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK (Android)
        script: flutter build apk --release
      - name: Build IPA (iOS)
        script: flutter build ipa --release --export-options-plist=ExportOptions.plist
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa
