workflows:
  ios-release:
    name: Build iOS Release without Mac
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.example.sansebassms"  # reemplaza con tu bundle ID
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Flutter clean
        script: |
          flutter clean

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    code_signing:
      use_automatic_signing: true

    publishing:
      app_store_connect:
        auth: integration  # usa las credenciales .p8 cargadas en Codemagic
        submit_to_testflight: true
        beta_groups:
          - SansebassmsTesters  # opcional, nombre del grupo de testers si tienes uno
