# Codemagic workflow configuration for iOS release builds
workflows:
  ios_release:
    name: iOS Release (Xcode 16.2)
    environment:
      xcode: 16.2
      flutter: stable
      vars:
        BUNDLE_ID: com.example.sansebassms
        APPLE_TEAM_ID: 7QWJ8R3ZB5
        CERTIFICATE_P12_BASE64: $CERTIFICATE_P12_BASE64
        P12_PASSWORD: $P12_PASSWORD
        KEYCHAIN_PASSWORD: $KEYCHAIN_PASSWORD
      groups:
        - app_store_connect
    scripts:
      - name: Pre-build (deps, pods, firma, logging)
        script: |
          chmod +x ./pre-build.sh
          ./pre-build.sh
      - name: Setup signing
        script: |
          chmod +x ./setup-signing.sh
          ./setup-signing.sh
      - name: Build IPA
        script: |
          chmod +x ./build-ipa.sh
          ./build-ipa.sh
    artifacts:
      - build/ios/ipa/*.ipa
      - codemagic_prebuild.log
      - codemagic_setup_signing.log
      - codemagic_build_ipa.log
      - artifacts/*
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
