workflows:
  ios-release:
    name: iOS Release
    environment:
      groups:
        - app_store_connect   # incluye la variable GOOGLE_SERVICE_INFO_PLIST_B64
      xcode: latest
      cocoapods: default
    scripts:
      - name: Setup signing
        script: ./setup-signing.sh
      - name: Pre-build
        script: ./pre-build.sh
      - name: Build IPA
        script: ./build-ipa.sh
      - name: Post-build
        script: ./post-build.sh

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - build/ios/ipa/*.app.dSYM.zip

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY      # contenido del archivo .p8
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER    # Key ID (ej: 43Z3JZ75L6)
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID      # Issuer ID (UUID)
        submit_to_testflight: true

