workflows:
  build_ios_only:
    name: Build iOS and publish to App Store
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_STORE_ID: 6749592028
        BUNDLE_ID: com.example.sansebassms
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
    publishing:
      app_store_connect:
        authentication: integration
        app_id: $APP_STORE_ID
        bundle_identifier: $BUNDLE_ID
        submit_to_testflight: true
        submit_to_app_store: false
