workflows:
  ios-release:
    name: iOS Release
    environment:
      groups:
        - app_store_connect       # contiene GOOGLE_SERVICE_INFO_PLIST y claves ASC
      xcode: latest
      cocoapods: default

    scripts:
      - name: Generar GoogleService-Info.plist
        script: |
          set -euxo pipefail
          echo "=== INICIO: GoogleService-Info.plist ==="
          PLIST_PATH="ios/Runner/GoogleService-Info.plist"
          mkdir -p ios/Runner
          VAR="${GOOGLE_SERVICE_INFO_PLIST:-}"
          if [[ -z "$VAR" ]]; then
            echo "GOOGLE_SERVICE_INFO_PLIST vacío"; exit 1
          fi
          if (printf '%s' "$VAR" | tr -d '\r' | base64 --decode > "$PLIST_PATH" 2>/dev/null) || \
             (printf '%s' "$VAR" | tr -d '\r' | base64 -D        > "$PLIST_PATH" 2>/dev/null); then
            echo "Decodificado Base64 a $PLIST_PATH"
          else
            echo "No se pudo decodificar GOOGLE_SERVICE_INFO_PLIST"; exit 1
          fi
          ls -l "$PLIST_PATH"
          head -n 20 "$PLIST_PATH"
          echo "=== FIN: GoogleService-Info.plist ==="

      - name: Configurar firma automática
        script: |
          set -euxo pipefail
          echo "=== INICIO: setup-signing ==="
          ./setup-signing.sh
          echo "=== FIN: setup-signing ==="

      - name: Instalar dependencias y CocoaPods
        script: |
          set -euxo pipefail
          echo "=== INICIO: deps & pods ==="
          flutter clean
          flutter pub get
          if grep -q "platform :ios" ios/Podfile; then
            sed -i.bak "s/platform :ios, '.*/platform :ios, '15.0'/" ios/Podfile || true
          else
            echo "platform :ios, '15.0'" >> ios/Podfile
          fi
          cd ios
          pod repo update
          pod install
          cd ..
          test -f ios/Runner.xcworkspace/contents.xcworkspacedata
          echo "=== FIN: deps & pods ==="

      - name: Compilar IPA release
        script: |
          set -euxo pipefail
          echo "=== INICIO: flutter build ipa ==="
          xcode-project use-profiles
          flutter build ipa --release
          echo "=== FIN: flutter build ipa ==="

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/Podfile.lock
      - ios/Runner.xcworkspace/**
      - "flutter_*.log"
      - "**/xcpretty*.log"
      - "**/*.xcresult"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

