workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: 16.2
      cocoapods: 1.16.2
      groups:
        - app_store_connect
    scripts:
      - name: Pre-build
        script: ./pre-build.sh
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist ExportOptions.plist
      - name: Publish to TestFlight
        script: |
          app-store-connect publish \
            --api-key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            build/ios/ipa/*.ipa
    artifacts:
      - build/ios/ipa/*.ipa
