workflows:
  build-ios-without-mac:
    name: Build iOS app without Mac
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.example.sansebassms"
        APP_STORE_CONNECT_ISSUER_ID: "0bae98e1-a493-4ddc-ab5d-cdb87b225a1b"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "43Z3JZ75L6"
        APP_STORE_CONNECT_PRIVATE_KEY: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRT1RhSkVDeE51QWQ5RDFkNFQKM1JIblNudmEvZTVWNnZab2JUcFdvdFRQS21nQ2dZSUtvWkl6ajBEQVFlaFJBTkNBQVJFVjJLczJYT0VkSWxDCklWU0wva1JkMGgzWXpNem01ZjRYclZzSWpHTDE1UCsxVkNkQ3F6U3B4M29rdlRVOE1weVlRR25PR0J6ODF5dVMCQkVRRy9GUDIKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo="
    integrations:
      app_store_connect: CodemagicKey
    triggering:
      events:
        - push
    scripts:
      - name: Pre-cache and clean
        script: |
          flutter precache --ios
          flutter pub get
          flutter clean

      - name: Patch missing Flutter.podspec
        script: |
          PODSPEC_SOURCE="$FLUTTER_ROOT/bin/cache/artifacts/engine/ios/Flutter.podspec"
          PODSPEC_TARGET="ios/Flutter/Flutter.podspec"
          if [ -f "$PODSPEC_SOURCE" ]; then
            echo "✔ Copiando Flutter.podspec al proyecto..."
            mkdir -p ios/Flutter
            cp "$PODSPEC_SOURCE" "$PODSPEC_TARGET"
          else
            echo "❌ No se encontró Flutter.podspec en $PODSPEC_SOURCE"
            exit 1
          fi

      - name: Build IPA for App Store
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
