workflows:
  ios-build-and-publish:
    name: iOS Build and Publish to App Store
    max_build_duration: 45
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials

      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.sansebassms"
        APP_STORE_APPLE_ID: 6749592028
        APP_STORE_CONNECT_ISSUER_ID: "0bae98e1-a493-4ddc-ab5d-cdb87b225a1b"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "43Z3JZ75L6"

    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Check ios/ contents
        script: |
          echo "Contenido de ios/"
          ls -la ios

      - name: Set up keychain
        script: |
          keychain initialize

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key "$CERTIFICATE_PRIVATE_KEY"

      - name: Use system default keychain
        script: |
          keychain add-certificates

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      # Nuevo paso: asegura que los archivos nativos estén generados antes de compilar
      - name: Ensure GeneratedPluginRegistrant is created
        script: |
          flutter clean
          flutter pub get
          flutter build ios --debug

      # Paso opcional, desactivado por ahora
      # - name: Increment build number
      #   script: |
      #     agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID") + 1))

      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false

      email:
        recipients:
          - amtoniosazon@gmail.com
        notify:
          success: true
          failure: true
