workflows:
  ios-build-and-publish:
    name: iOS Build and Publish to App Store
    max_build_duration: 45
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials  # Este grupo debe contener 3 variables:
                                 # APP_STORE_CONNECT_ISSUER_ID
                                 # APP_STORE_CONNECT_KEY_IDENTIFIER
                                 # APP_STORE_CONNECT_PRIVATE_KEY (.p8 en texto plano)
      vars:
        BUNDLE_ID: "com.example.sansebassms"
        APP_STORE_APPLE_ID: 6749592028
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Set up keychain
        script: |
          keychain initialize

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"

      - name: Add signing certificates
        script: |
          keychain add-certificates

      - name: Set up Xcode project for codesigning
        script: |
          xcode-project use-profiles

      - name: Increment build number
        script: |
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID") + 1))

      - name: Build IPA
        script: |
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
      email:
        recipients:
          - antoniosazon@gmail.com
        notify:
          success: true
          failure: true
