workflows:
  ios-release:
    environment:
      groups:
        - app_store_connect
      xcode: latest
    scripts:
      - name: Generar GoogleService-Info.plist (seguro)
        script: |
          set -euo pipefail
          bash tool/prebuild_plist.sh

      - name: Instalar dependencias y CocoaPods
        script: |
          set -euo pipefail
          mkdir -p build_logs
          echo "== POD INSTALL ==" | tee -a build_logs/build.log
          flutter pub get 2>&1 | tee -a build_logs/build.log
          cd ios
          pod install 2>&1 | tee -a ../build_logs/build.log
          cd ..

      - name: Compilar IPA release
        script: |
          set -euo pipefail
          mkdir -p build_logs
          echo "== FLUTTER BUILD ==" | tee -a build_logs/build.log
          flutter build ipa --release --build-number=$BUILD_NUMBER 2>&1 | tee -a build_logs/build.log

    artifacts:
      - build/ios/ipa/*.ipa
      - build_logs/**

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
