workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: 🔄 Limpiar y reinstalar pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod cache clean --all
          pod install
          cd ..
      - name: 📦 Obtener dependencias Flutter
        script: flutter pub get
      - name: 🚀 Compilar aplicación iOS (sin firma)
        script: flutter build ios --release
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/Runner.app
      - build/ios/archive/*.xcarchive
    publishing:
      email:
        recipients:
          - tu_correo@ejemplo.com
