workflows:
  ios-build-and-publish:
    name: iOS Build and Publish to App Store
    max_build_duration: 45
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.sansebassms"
        APP_STORE_CONNECT_ISSUER_ID: "0bae98e1-a493-4ddc-ab5d-cdb87b225a1b"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "43Z3JZ75L6"
      groups:
        - app_store_credentials
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Create Flutter.podspec manually if missing
        script: |
          PODSPEC_PATH="$FLUTTER_ROOT/bin/cache/artifacts/engine/ios/Flutter.podspec"
          if [ ! -f "$PODSPEC_PATH" ]; then
            echo "⚠️ Flutter.podspec no encontrado, creando..."
            mkdir -p "$(dirname "$PODSPEC_PATH")"
            cat > "$PODSPEC_PATH" <<EOF
Pod::Spec.new do |s|
  s.name             = 'Flutter'
  s.version          = '1.0.0'
  s.summary          = 'Flutter Engine'
  s.description      = <<-DESC
    flutter engine framework
  DESC
  s.homepage         = 'https://flutter.dev'
  s.license          = { :type => 'BSD' }
  s.author           = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
  s.source           = { :http => 'https://github.com/flutter/flutter' }
  s.documentation_url = 'https://flutter.dev/docs'
  s.platform         = :ios, '8.0'
  s.vendored_frameworks = 'Flutter.framework'
end
EOF
          fi

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Set up keychain and code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"
          keychain add-certificates

      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
          xcode-project use-profiles
          xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner

      - name: Publish to App Store Connect
        script: |
          app-store-connect publish \
            --path build/ios/ipa/*.ipa \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"

    artifacts:
      - build/ios/ipa/*.ipa
