workflows:
  build_ios_only:
    name: Build iOS only
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.example.sansebassms  # <-- Ajusta si es diferente
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
