workflows:
  generate-ios-artifacts:
    name: Generate iOS Artifacts for GitHub
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS to generate native artifacts (no signing)
        script: |
          flutter build ios --no-codesign
    artifacts:
      - ios/Flutter/Flutter.podspec
      - ios/Runner/GeneratedPluginRegistrant.*
      - ios/Flutter/Generated.xcconfig
      - ios/Flutter/flutter_export_environment.sh
      - build/ios/iphoneos/Runner.app.dSYM
      - build/**/Build/**/*.log
