# Codemagic workflow configuration for iOS release builds
workflows:
  ios_release:
    name: iOS Release (Xcode 16.2)
    environment:
      xcode: 16.2
      flutter: stable
      vars:
        BUNDLE_ID: com.example.sansebassms
      groups:
        - app_store_connect
        - ios_signing
    scripts:
      - name: Pre-build (deps, pods, firma, logging)
        script: |
          chmod +x ./pre-build.sh
          ./pre-build.sh
      - name: Setup signing
        script: |
          bash -xe ./setup-signing.sh
      - name: Build IPA
        script: |
          bash -xe ./build-ipa.sh
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - codemagic_setup_signing.log
      - codemagic_build_ipa.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
