workflows:
  ios-release:
    name: iOS Release
    environment:
      groups:
        - app_store_connect   # incluye la variable GOOGLE_SERVICE_INFO_PLIST_B64
      xcode: latest
      cocoapods: default
    scripts:
      - name: Prepare GoogleService-Info.plist
        script: |
          set -euo pipefail
          PLIST_PATH="ios/Runner/GoogleService-Info.plist"

          if [[ -n "${GOOGLE_SERVICE_INFO_PLIST_B64:-}" ]]; then
            echo "Processing GOOGLE_SERVICE_INFO_PLIST_B64..."
            mkdir -p ios/Runner
            if printf '%s' "$GOOGLE_SERVICE_INFO_PLIST_B64" | base64 --decode > "$PLIST_PATH.tmp" 2>/dev/null; then
              mv "$PLIST_PATH.tmp" "$PLIST_PATH"
              echo "Decoded Base64 plist"
            elif grep -q '<plist' <<<"$GOOGLE_SERVICE_INFO_PLIST_B64"; then
              printf '%s' "$GOOGLE_SERVICE_INFO_PLIST_B64" > "$PLIST_PATH"
              echo "Wrote raw XML plist"
            else
              echo "Invalid GOOGLE_SERVICE_INFO_PLIST_B64; Firebase will be disabled"
              rm -f "$PLIST_PATH.tmp"
            fi
            ls -l "$PLIST_PATH" 2>/dev/null || true
          fi

          if [[ ! -f "$PLIST_PATH" ]]; then
            echo "⚠️ $PLIST_PATH not found. Running WITHOUT Firebase."
            NEW_DEFINE=$(printf 'NO_FIREBASE=true' | base64)
            if [[ -n "${DART_DEFINES:-}" ]]; then
              export DART_DEFINES="${DART_DEFINES},${NEW_DEFINE}"
            else
              export DART_DEFINES="${NEW_DEFINE}"
            fi
          else
            echo "✅ Found $PLIST_PATH (Firebase ON)"
          fi

      - name: Flutter build IPA
        script: |
          # Ajustar target para que corra en iOS 15+
          if grep -q "platform :ios" ios/Podfile; then
            sed -i.bak "s/platform :ios, '.*'/platform :ios, '15.0'/" ios/Podfile || true
          else
            echo "platform :ios, '15.0'" >> ios/Podfile
          fi
          flutter pub get
          flutter build ipa --release --build-number=3

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY      # contenido del archivo .p8
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER    # Key ID (ej: 43Z3JZ75L6)
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID      # Issuer ID (UUID)
        submit_to_testflight: true

