workflows:
  build-ios-without-mac:
    name: Build iOS app without Mac
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.example.sansebassms"
        APP_STORE_CONNECT_ISSUER_ID: "0bae98e1-a493-4ddc-ab5d-cdb87b225a1b"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "43Z3JZ75L6"
        APP_STORE_CONNECT_PRIVATE_KEY: |
          LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRT1RhSkVDeE51QWQ5RDFkNFQKM1JIblNudmEvZTVWNnZab2JUcFdvdFRQS21nQ2dZSUtvWkl6ajBEQVFlaFJBTkNBQVJFVjJLczJYT0VkSWxDCklWU0wva1JkMGgzWXpNem01ZjRYclZzSWpHTDE1UCsxVkNkQ3F6U3B4M29rdlRVOE1weVlRR25PR0J6ODF5dVMCQkVRRy9GUDIKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
    integrations:
      app_store_connect: CodemagicKey

    signing:
      certificates:
        - distribution_type: app_store
          bundle_id: "com.example.sansebassms"
          type: automatic  # Activar firma automática

    triggering:
      events:
        - push

    scripts:
      - name: Pre-cache and clean
        script: |
          flutter precache --ios
          flutter pub get
          flutter clean

      - name: Generate Flutter.podspec manually
        script: |
          mkdir -p ios/Flutter
          cat > ios/Flutter/Flutter.podspec <<EOF
          Pod::Spec.new do |s|
            s.name             = 'Flutter'
            s.version          = '1.0.0'
            s.summary          = 'Flutter framework'
            s.description      = <<-DESC
                                  Flutter iOS engine
                                 DESC
            s.homepage         = 'https://flutter.dev'
            s.license          = { :type => 'BSD' }
            s.author           = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
            s.source           = { :http => 'https://flutter.dev' }
            s.source_files     = '**/*'
            s.public_header_files = '**/*.h'
            s.module_map       = 'module.modulemap'
            s.platform         = :ios, '11.0'
          end
          EOF

      - name: Build IPA for App Store
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
