workflows:
  build_ios_only:
    name: Build iOS only
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.example.sansebassms
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    code_signing:
      certificates:
        - certificate_name: ios_distribution  # <-- este es el nombre que diste al guardar el certificado
          set_up_automatic_code_signing: true
