workflows:
  generate-ios-artifacts:
    name: Generate iOS Artifacts for GitHub
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Build iOS to generate native artifacts (no signing)
        script: |
          flutter build ios --no-codesign

      - name: 🔍 Revisar contenido de ios/Flutter y ios/Runner
        script: |
          echo "--- Contenido de ios/Flutter/"
          ls -la ios/Flutter || echo "⚠️ ios/Flutter no existe"
          
          echo "--- Contenido de ios/Runner/"
          ls -la ios/Runner || echo "⚠️ ios/Runner no existe"

    artifacts:
      - ios/Flutter/Flutter.podspec
      - ios/Flutter/Generated.xcconfig
      - ios/Flutter/flutter_export_environment.sh
      - ios/Runner/GeneratedPluginRegistrant.h
      - ios/Runner/GeneratedPluginRegistrant.m
      - build/ios/iphoneos/Runner.app.dSYM
