name: sansebassms
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0

  sqflite: ^2.3.0
  path: ^1.9.0

# Pod build fix for Xcode 16
# Keeping firebase packages current ensures their podspecs do not include
# deprecated compiler flags (e.g. `GCC_WARN_INHIBIT_ALL_WARNINGS`).

  shared_preferences: 2.2.3
  permission_handler: 12.0.1
  cupertino_icons: 1.0.8
  flutter_launcher_icons: 0.14.4
  flutter_local_notifications: 17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/icono_app.png

ios:
  deployment_target: 15.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icono_app.png"
