name: sansebassms
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase - alineados para iOS SDK 12.1.0+
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.0
  firebase_messaging: ^16.1.0

  # Otros paquetes
  shared_preferences: ^2.0.0
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icono_app.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icono_app.png"
