name: sms_advanced
description: Paquete local para envío de SMS sin depender de pub.dev
version: 1.0.0
homepage: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sms.advanced
        pluginClass: SmsAdvancedPlugin
