name: iOS Build (Flutter, unsigned)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1. Descargar el código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Instalar Flutter estable
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3. Verificar versión de Flutter
      - name: Flutter version
        run: flutter --version

      # 4. Obtener dependencias de Dart/Flutter
      - name: Flutter pub get
        run: flutter pub get

      # 5. Instalar CocoaPods
      - name: Ensure CocoaPods
        run: |
          sudo gem install cocoapods -N || true
          pod --version

      # 6. Limpiar y reinstalar pods con el nuevo Podfile
      - name: Clean & reinstall pods
        run: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Flutter/Flutter.framework
          flutter pub get
          cd ios && pod install --repo-update && cd ..

      # (Opcional) Mostrar el Podfile y pods instalados para debug
      - name: Show Podfile & pod list
        run: |
          sed -n '1,200p' ios/Podfile
          cd ios && pod list

      # 7. Construir IPA sin firmar
      - name: Build IPA (no codesign)
        run: flutter build ipa --release --no-codesign

      # 8. Subir el .ipa como artefacto descargable
      - name: Upload artifact (.ipa)
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-unsigned
          path: build/ios/ipa/*.ipa
