name: iOS Signed Build & TestFlight

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'   # p.ej. v1.0.0

jobs:
  ios:
    runs-on: macos-latest
    timeout-minutes: 60
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Asegura Xcode 16.2 (SDK iOS 18.x)
      - name: Select Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app
          xcodebuild -version
          xcodebuild -showsdks | grep iPhoneOS || true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods -N
          cd ios
          pod repo update
          pod install --repo-update

      # ⬇️ NUEVO: Bump de mínimos (Runner + AppFramework) a 15.0
      - name: Bump iOS minimums (Runner + AppFramework)
        shell: bash
        run: |
          /usr/bin/sed -i '' -E 's/(IPHONEOS_DEPLOYMENT_TARGET = )([0-9]+\.[0-9]+);/\115.0;/g' ios/Runner.xcodeproj/project.pbxproj
          /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 15.0" ios/Flutter/AppFrameworkInfo.plist || true

      # Limpia cualquier -G que puedan meter Pods o configs antiguas
      - name: Strip illegal -G from Pod xcconfigs
        shell: bash
        run: |
          set -e
          # Todas las .xcconfig de Pods (soporta '-G' y '-G 0|1|..')
          find ios/Pods -name "*.xcconfig" -print0 | xargs -0 /usr/bin/sed -i '' -E 's/(^|[[:space:]])-G([[:space:]]+[0-9]+)?([[:space:]]|$)/ /g' || true
          # Por si queda en el pbxproj del Runner dentro de OTHER_CFLAGS
          /usr/bin/sed -i '' -E 's/(OTHER_CFLAGS = [^;"]*)-G([[:space:]]*[0-9]+)?([^;"]*;)/\1\3/g' ios/Runner.xcodeproj/project.pbxproj || true

      - name: Sanity check CFLAGS (no -G)
        shell: bash
        run: |
          if grep -R --include=\*.{xcconfig,pbxproj} -nE '(^| )-G( |$)|(^| )-G[[:space:]]+[0-9]+' ios; then
            echo "Aún aparece -G en alguna config"; exit 1
          else
            echo "OK: no se ve -G en configs";
          fi

      # Limpieza de DerivedData para un build fresco
      - name: Clean DerivedData (fresh build)
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Install fastlane + jq
        run: |
          gem install fastlane -N
          brew install jq

      - name: Decode signing assets
        shell: bash
        run: |
          printf "%s" "${{ secrets.P12_BASE64 }}" | base64 --decode > cert.p12
          printf "%s" "${{ secrets.P12_PASSWORD }}" > p12pass.txt
          printf "%s" "${{ secrets.PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > profile.mobileprovision
          printf "%s" "${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}" | base64 --decode > AuthKey.p8

      - name: Verify P12 (hash + password)
        shell: bash
        run: |
          echo "Runner SHA256:"; shasum -a 256 cert.p12
          openssl pkcs12 -in cert.p12 -nokeys -passin file:p12pass.txt -info >/dev/null

      # Import fiable: reempaquetar el P12 y meterlo en un keychain dedicado
      - name: Create keychain & import identity (repack PKCS#12)
        shell: bash
        env:
          KEYCHAIN_PASSWORD: actions
        run: |
          set -e
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -lut 21600 build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain

          # 1) Extrae cert y key del P12 original
          openssl pkcs12 -in cert.p12 -clcerts -nokeys -passin file:p12pass.txt -out dist-cert.cer
          openssl pkcs12 -in cert.p12 -nocerts -nodes -passin file:p12pass.txt -out dist-key.pem
          awk '/-----BEGIN .*PRIVATE KEY-----/,/-----END .*PRIVATE KEY-----/' dist-key.pem > dist-key-only.pem

          # 2) Reempaqueta a PKCS#12 con pass temporal
          LOCAL_P12_PASS=$(openssl rand -hex 12)
          openssl pkcs12 -export \
            -inkey dist-key-only.pem \
            -in dist-cert.cer \
            -name "iOS Distribution (repacked)" \
            -out identity.p12 \
            -passout pass:${LOCAL_P12_PASS}

          # 3) Importa ese PKCS#12
          security import identity.p12 -k build.keychain -P "${LOCAL_P12_PASS}" -T /usr/bin/codesign -T /usr/bin/security -f pkcs12

          # 4) Usa sólo este keychain y da permisos de codesign
          security list-keychains -d user -s build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" build.keychain

          echo "Identidades de codesigning en el keychain:"
          security find-identity -v -p codesigning build.keychain || true

      - name: Install provisioning profile
        shell: bash
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< "$(security cms -D -i profile.mobileprovision)")
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision

      - name: Create ExportOptions.plist
        run: |
          cat > ExportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>uploadSymbols</key><true/>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>destination</key><string>export</string>
            <key>teamID</key><string>${{ secrets.APPLE_TEAM_ID }}</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${{ secrets.APP_IDENTIFIER }}</key>
              <string>Sansebassms AppStore Profile</string>
            </dict>
          </dict>
          </plist>
          EOF

      # FLUTTER_ROOT correcto en el runner (evita ruta de Windows)
      - name: Fix FLUTTER_ROOT for iOS build
        shell: bash
        run: |
          mkdir -p ios/Flutter
          if [ -f ios/Flutter/Generated.xcconfig ]; then
            /usr/bin/sed -i '' -E "s#^FLUTTER_ROOT=.*#FLUTTER_ROOT=${FLUTTER_ROOT}#g" ios/Flutter/Generated.xcconfig || true
          else
            cat > ios/Flutter/Generated.xcconfig <<EOF
          FLUTTER_ROOT=${FLUTTER_ROOT}
          EOF
          fi
          for cfg in ios/Flutter/Debug.xcconfig ios/Flutter/Release.xcconfig; do
            [ -f "$cfg" ] || touch "$cfg"
            grep -q 'Generated.xcconfig' "$cfg" || echo '#include? "Generated.xcconfig"' >> "$cfg"
          done
          echo "Usando $(grep ^FLUTTER_ROOT ios/Flutter/Generated.xcconfig)"

      # Archive sin firmar (evita perfiles en pods)
      - name: Archive with xcodebuild (unsigned)
        shell: bash
        run: |
          set -e
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath ../build/Runner.xcarchive \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=${{ secrets.APPLE_TEAM_ID }} \
            clean archive

      - name: Export IPA (sign)
        shell: bash
        run: |
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ios_export

      - name: Upload to TestFlight (fastlane pilot)
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        run: |
          KEY=$(jq -Rs . < AuthKey.p8)
          cat > api_key.json <<EOF
          {
            "key_id": "${{ secrets.APP_STORE_CONNECT_KEY_ID }}",
            "issuer_id": "${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}",
            "key": $KEY,
            "in_house": false
          }
          EOF
          IPA_PATH=$(ls build/ios_export/*.ipa | head -n 1)
          fastlane pilot upload --api_key_path api_key.json --ipa "$IPA_PATH" --skip_waiting_for_build_processing true

      - name: Upload signed IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-signed-ipa
          path: build/ios_export/*.ipa
