name: Build iOS IPA (Unsigned, locked)

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ios-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ios:
    runs-on: macos-14   # Xcode 15 (Swift 5.9)
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: stable

      - name: Flutter pub get (lock respected)
        run: flutter pub get

      # Primera vez: repo update para bajar podspecs
      - name: Install CocoaPods (first run)
        run: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Build IPA (unsigned)
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-unsigned
          path: build/ios/ipa/*.ipa
