name: iOS Signed Build & TestFlight

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'   # sube a TestFlight cuando etiquetes p.ej. v1.0.0

jobs:
  ios:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods -N
          cd ios
          pod install --no-repo-update

      - name: Install fastlane
        run: gem install fastlane -N

      - name: Decode signing assets
        shell: bash
        run: |
          printf "%s" "${{ secrets.P12_BASE64 }}" | base64 --decode > cert.p12
          printf "%s" "${{ secrets.PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > profile.mobileprovision
          printf "%s" "${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}" > AuthKey.p8
          printf "%s" "${{ secrets.P12_PASSWORD }}" > p12pass.txt

      # Verificación previa: el p12 es el correcto y la pass abre
      - name: Verify P12 (hash + password)
        shell: bash
        run: |
          echo "Runner SHA256:"
          shasum -a 256 cert.p12
          echo "Verificando que la contraseña abre el p12..."
          openssl pkcs12 -in cert.p12 -nokeys -passin file:p12pass.txt -info >/dev/null

      # EXTRAER cert y key con OpenSSL para evitar import directo del .p12
      - name: Extract cert & key with OpenSSL
        shell: bash
        run: |
          # Extrae el certificado (sin keys)
          openssl pkcs12 -in cert.p12 -clcerts -nokeys -passin file:p12pass.txt -out dist-cert.cer
          # Extrae la clave privada en PEM con pass temporal
          openssl pkcs12 -in cert.p12 -nocerts -passin file:p12pass.txt -passout pass:tmpkeypass -out dist-key.pem
          # Convierte la clave a PKCS#8 SIN contraseña (formato que entiende bien security)
          openssl pkcs8 -topk8 -inform PEM -outform PEM -in dist-key.pem -passin pass:tmpkeypass -nocrypt -out dist-key-pkcs8.pem
          # Calcula SHA1 del cert para set-key-partition-list
          CERT_SHA1=$(openssl x509 -in dist-cert.cer -noout -fingerprint -sha1 | sed 's/.*=//;s/://g' | tr '[:upper:]' '[:lower:]')
          echo "CERT_SHA1=$CERT_SHA1" > certsha1.env
          cat certsha1.env

      - name: Create dedicated keychain & import cert+key
        shell: bash
        run: |
          source certsha1.env
          security create-keychain -p "" build.keychain
          security set-keychain-settings -lut 21600 build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain

          # Importa el certificado (X.509)
          security import dist-cert.cer -k build.keychain -A -T /usr/bin/codesign -T /usr/bin/security -f x509

          # Importa la clave privada PKCS#8 SIN pass
          # (primero probamos como pkcs8, si falla probamos pemseq)
          security import dist-key-pkcs8.pem -k build.keychain -A -T /usr/bin/codesign -T /usr/bin/security -f pkcs8 -t priv \
          || security import dist-key-pkcs8.pem -k build.keychain -A -T /usr/bin/codesign -T /usr/bin/security -f pemseq -t priv

          # Da acceso a apple-tool/apple y asocia por SHA1
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain -Z "$CERT_SHA1"

          # (Opcional) Verifica que hay identidad de codesign disponible
          security find-identity -v -p codesigning build.keychain || true

      - name: Install provisioning profile
        shell: bash
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< "$(security cms -D -i profile.mobileprovision)")
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision

      - name: Create ExportOptions.plist
        run: |
          cat > ExportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>uploadSymbols</key><true/>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>destination</key><string>export</string>
            <key>teamID</key><string>${{ secrets.APPLE_TEAM_ID }}</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${{ secrets.APP_IDENTIFIER }}</key>
              <string>Sansebassms AppStore Profile</string>
            </dict>
          </dict>
          </plist>
          EOF

      - name: Build signed IPA for App Store
        run: flutter build ipa --release --export-options-plist=ExportOptions.plist

      - name: Upload to TestFlight (fastlane pilot)
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        run: |
          cat > api_key.json <<EOF
          {
            "key_id": "${{ secrets.APP_STORE_CONNECT_KEY_ID }}",
            "issuer_id": "${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}",
            "key": "$(cat AuthKey.p8)",
            "in_house": false
          }
          EOF
          IPA_PATH=$(ls build/ios/ipa/*.ipa | head -n 1)
          fastlane pilot upload --api_key_path api_key.json --ipa "$IPA_PATH" --skip_waiting_for_build_processing true

      - name: Upload signed IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-signed-ipa
          path: build/ios/ipa/*.ipa
