name: Build iOS Unsigned IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: flutter-pub-${{ hashFiles('**/pubspec.lock') }}

      - name: Cache CocoaPods
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/Library/Developer/Xcode/DerivedData
          key: pods-${{ hashFiles('ios/Podfile.lock') }}

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods (no repo update)
        run: |
          cd ios
          pod install
          cd ..

      - name: Build unsigned IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-unsigned
          path: build/ios/ipa/*.ipa
