name: Build iOS unsigned IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # o el que uses localmente
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Pod repo update (solo primera vez o si cambias Podfile)
        run: |
          cd ios
          pod repo update
          cd ..

      - name: Build IPA (no codesign)
        run: |
          flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned
          path: build/ios/ipa/*.ipa
